### ISSUE TITLE
Error: External Exception rs2_pipeline_start_with_config(pipe:0000026A3347EC10, config:0000026A3347EFB0)

### ISSUE THREAD

**Issue by nirmalsnair** [ababilinski/realsense-apriltags-calibration-unity#3]
🤗 Thanks for the code!

I connected an Intel RealSense D457 depth camera and it is being detected (with the serial number) on the first 'Devices' screen. But on clicking 'Continue' and going to the next screen, I am getting the following error:

```
ExternalException: rs2_pipeline_start_with_config(pipe:0000026A3347EC10, config:0000026A3347EFB0)
Rethrow as Exception: Couldn't resolve requests
Intel.RealSense.ErrorMarshaler.MarshalNativeToManaged (System.IntPtr pNativeData) (at <cb539c8577184d8bb3db94250e9792dc>:0)
Intel.RealSense.Pipeline.Start (Intel.RealSense.Config cfg) (at <cb539c8577184d8bb3db94250e9792dc>:0)
RsDevice.OnEnable () (at Assets/RealSenseSDK2.0/Scripts/RsDevice.cs:71)
UnityEngine.GameObject:SetActive(Boolean)
Babilinapps.RealSenseAprilTags.Examples.RsDeviceSpawner:SpawnDevices(List`1) (at Assets/RealSenseAprilTags/Examples/CameraCalibration/Scripts/UI/Controllers/RsDeviceSpawner.cs:41)
Babilinapps.RealSenseAprilTags.Examples.<SpawnDevices>d__9:MoveNext() (at Assets/RealSenseAprilTags/Examples/CameraCalibration/Scripts/UI/Controllers/CalibrationController.cs:49)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
```

| Info | |
| --- | --- |
Camera | Intel RealSense D457
Unity version | 2020.3.4f1
Intel RealSense SDK version | WIN10-2.54.2.5684
Operating System | Windows 10

**Comment by ababilinski** [comment]
Hi Nirmal,
Can you try running the Standalone RealSense Viewer and see if the device
is connected via usb 3?

**Comment by nirmalsnair** [comment]
Apologies for the delayed update. As you suggested the issue was indeed related to the USB cable and port. Switching to a different cable and port resolved the problem.

Notably, in the Intel RealSense Viewer, both the RGB and Depth streams function irrespective of the cable and port used. However, in Unity, the streams only operate when connected via USB 3.

Reference: https://github.com/IntelRealSense/librealsense/issues/10423#issuecomment-1851830970
